name: Auto Update All MRS Ruleset

on:
  schedule:
    - cron: '0 2 * * *' # 北京时间每天上午 10:00 (UTC 2:00) 自动运行
  workflow_dispatch:

jobs:
  update-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all Rulesets
        run: |
          # 1. 创建规范化的本地存储文件夹
          mkdir -p mihomo/domain
          mkdir -p mihomo/ipcidr

          # =================================================================
          # 2. 批量抓取【域名规则集】 (共 31 条，存放至 mihomo/domain)
          # =================================================================
          echo "正在同步域名规则集..."
          wget -O mihomo/domain/apple.mrs "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/apple.mrs"
          wget -O mihomo/domain/Telegram_domain.mrs "https://github.com/ACL4SSR/ACL4SSR/raw/refs/heads/master/Clash/mrs/Telegram_domain.mrs"
          wget -O mihomo/domain/youtube.mrs "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/youtube.mrs"
          wget -O mihomo/domain/apple-cn.mrs "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/apple-cn.mrs"
          wget -O mihomo/domain/LocalAreaNetwork_domain.mrs "https://github.com/ACL4SSR/ACL4SSR/raw/refs/heads/master/Clash/mrs/LocalAreaNetwork_domain.mrs"
          wget -O mihomo/domain/ChinaDomain_domain.mrs "https://github.com/ACL4SSR/ACL4SSR/raw/refs/heads/master/Clash/mrs/ChinaDomain_domain.mrs"
          wget -O mihomo/domain/google.mrs "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/google.mrs"
          wget -O mihomo/domain/Microsoft_domain.mrs "https://github.com/ACL4SSR/ACL4SSR/raw/refs/heads/master/Clash/mrs/Microsoft_domain.mrs"
          wget -O mihomo/domain/TikTok_domain.mrs "https://github.com/ACL4SSR/ACL4SSR/raw/refs/heads/master/Clash/mrs/TikTok_domain.mrs"
          wget -O mihomo/domain/UnBan_domain.mrs "https://github.com/ACL4SSR/ACL4SSR/raw/refs/heads/master/Clash/mrs/UnBan_domain.mrs"
          wget -O mihomo/domain/ChinaMedia_domain.mrs "https://github.com/ACL4SSR/ACL4SSR/raw/refs/heads/master/Clash/mrs/ChinaMedia_domain.mrs"
          wget -O mihomo/domain/BanAD_domain.mrs "https://github.com/ACL4SSR/ACL4SSR/raw/refs/heads/master/Clash/mrs/BanAD_domain.mrs"
          wget -O mihomo/domain/Twitter_domain.mrs "https://github.com/ACL4SSR/ACL4SSR/raw/refs/heads/master/Clash/mrs/Twitter_domain.mrs"
          wget -O mihomo/domain/meta.mrs "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/meta.mrs"
          wget -O mihomo/domain/cn_geosite.mrs "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/cn.mrs"
          wget -O mihomo/domain/category-doh.mrs "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-doh.mrs"
          wget -O mihomo/domain/category-httpdns-cn.mrs "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-httpdns-cn.mrs"
          wget -O mihomo/domain/private.mrs "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/private.mrs"
          wget -O mihomo/domain/apple-tvplus.mrs "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/apple-tvplus.mrs"
          wget -O mihomo/domain/google-fcm.mrs "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/googlefcm.mrs"
          wget -O mihomo/domain/github.mrs "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/github.mrs"
          wget -O mihomo/domain/category-social-media-not-cn.mrs "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-social-media-!cn.mrs"
          wget -O mihomo/domain/geolocation-not-cn.mrs "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/geolocation-!cn.mrs"
          wget -O mihomo/domain/scholar.mrs "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-scholar-!cn.mrs"
          wget -O mihomo/domain/fakeip-filter.mrs "https://github.com/DustinWin/ruleset_geodata/releases/download/mihomo-ruleset/fakeip-filter.mrs"
          wget -O mihomo/domain/trackers_domain.mrs "https://github.com/yhlh9982/clash-rules/releases/download/tracker-rules/trackers_domain.mrs"
          wget -O mihomo/domain/spotify.mrs "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/spotify.mrs"
          wget -O mihomo/domain/openai.mrs "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/openai.mrs"
          wget -O mihomo/domain/openai-ads.mrs "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/openai@ads.mrs"
          wget -O mihomo/domain/ai_domain_acl4ssr.mrs "https://github.com/ACL4SSR/ACL4SSR/raw/refs/heads/master/Clash/mrs/AI_domain.mrs"
          # 最后一个是唯一的纯文本格式直连列表
          wget -O mihomo/domain/Custom_Direct.txt "https://github.com/Aethersailor/Custom_OpenClash_Rules/raw/main/rule/Custom_Direct.list"

          # =================================================================
          # 3. 批量抓取【IP规则集】 (共 11 条，存放至 mihomo/ipcidr)
          # =================================================================
          echo "正在同步 IP 规则集..."
          wget -O mihomo/ipcidr/LocalAreaNetwork_ip.mrs "https://github.com/ACL4SSR/ACL4SSR/raw/refs/heads/master/Clash/mrs/LocalAreaNetwork_ip.mrs"
          wget -O mihomo/ipcidr/ChinaDomain_ip.mrs "https://github.com/ACL4SSR/ACL4SSR/raw/refs/heads/master/Clash/mrs/ChinaDomain_ip.mrs"
          wget -O mihomo/ipcidr/Telegram_ip.mrs "https://github.com/ACL4SSR/ACL4SSR/raw/refs/heads/master/Clash/mrs/Telegram_ip.mrs"
          wget -O mihomo/ipcidr/google_ip.mrs "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/google.mrs"
          wget -O mihomo/ipcidr/apple_ip.mrs "https://github.com/ACL4SSR/ACL4SSR/raw/refs/heads/master/Clash/mrs/Apple_ip.mrs"
          wget -O mihomo/ipcidr/facebook_ip.mrs "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/facebook.mrs"
          wget -O mihomo/ipcidr/cn_geoip.mrs "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/cn.mrs"
          wget -O mihomo/ipcidr/private_ip.mrs "https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/private.mrs"
          wget -O mihomo/ipcidr/trackers_ip.mrs "https://github.com/yhlh9982/clash-rules/releases/download/tracker-rules/trackers_ip.mrs"

          # 注意：跳过了你原本清单中指向 hutaorules 本身的 6 个自建规则（Dev, Speedtest, AiIP, ChinaIP, TrackingIP, YoutubeIP），防止自己覆盖自己产生死循环。

      - name: Commit and Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # 将刚才更新的所有文件暂存
          git add mihomo/
          
          # 检查是否有文件更新，有就提交，没有就直接跳过
          git commit -m "自动同步全网上游最新 MRS 规则集 [skip ci]" || exit 0
          git push
